name: fsit_flutter_task_ecommerce
description: "Simple Ecommerce app for task in FIST company"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #Design
  text_scroll: 0.2.0
  flutter_svg: 2.0.10+1
  vector_graphics: 1.1.11
  vector_graphics_compiler: 1.1.11
  lottie: ^3.1.3

  #Responsive
  flutter_screenutil: 5.9.3
  auto_size_text: 3.0.0
  #Utils
  country_picker: 2.0.27
  faker: ^2.2.0

  #conffeti:
  confetti: ^0.8.0
  #Translation
  easy_localization: 3.0.8
  intl: 0.20.2

  #State Management
  flutter_bloc: 8.1.3
  equatable: 2.0.7
  reactive_forms: ^18.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  #Navigation
  go_router: ^14.6.2

  share_plus: ^10.1.2
  flutter_image_compress: ^2.4.0

  #Camera
  camerawesome: ^2.5.0
  path_provider: ^2.1.5

  #Image Viewer
  photo_view: ^0.15.0
  permission_handler: ^11.3.1
  image_picker: ^1.2.1

  #Voice Recording
  audio_waveforms: ^1.0.5

  #network
  http: ^1.2.2
  dio: ^5.4.0
  pretty_dio_logger: ^1.4.0
  injectable: ^2.4.1
  dartz: ^0.10.1

  #Storage
  shared_preferences: ^2.3.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  carousel_slider: ^5.1.1

  #Bottom Navigation
  google_nav_bar: ^5.0.7
  tutorial_coach_mark: ^1.3.3


  #Animation
  flutter_animate: ^4.5.2
  shimmer_animation: ^2.2.2
  skeletonizer: ^2.1.0+1

  #Side Menu
  flutter_side_menu: ^0.5.41

  #Calendar
  calendar_date_picker2: ^2.0.1
  board_datetime_picker: ^2.8.4
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.0
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.11.0
  flutter_lints: ^6.0.0
  injectable_generator: ^2.4.1
  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0

#* Launcher icon config â€” uses assets/logo/logo.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/logo.png"
  adaptive_icon_foreground_inset: 16
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#2D5F4C"
    theme_color: "#2D5F4C"
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"

flutter:

  uses-material-design: true



  # Assets
  assets:
    - assets/logo/
    - assets/lottie/
    - assets/images/
    - assets/images/png/
    - assets/images/icons/
    - assets/translation/
    - assets/images/status/

  fonts:
      - family: Baloo
        fonts:
          - asset: assets/fonts/baloo/baloo.regular.ttf
      - family: Baloo 2
        fonts:
          - asset: assets/fonts/baloo/Baloo2-VariableFont_wght.ttf
      - family: Cormorant Garamond
        fonts:
          - asset: assets/fonts/cormorant_garamond/CormorantGaramond-VariableFont_wght.ttf
      - family: Sora
        fonts:
          - asset: assets/fonts/sora/Sora-VariableFont_wght.ttf
          - asset: assets/fonts/sora/static/Sora-Thin.ttf
            weight: 100
          - asset: assets/fonts/sora/static/Sora-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/sora/static/Sora-Light.ttf
            weight: 300
          - asset: assets/fonts/sora/static/Sora-Regular.ttf
            weight: 400
          - asset: assets/fonts/sora/static/Sora-Medium.ttf
            weight: 500
          - asset: assets/fonts/sora/static/Sora-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/sora/static/Sora-Bold.ttf
            weight: 700
          - asset: assets/fonts/sora/static/Sora-ExtraBold.ttf
            weight: 800

flutter_gen:
  output: lib/gen/
  line_length: 120
  integrations:
    flutter_svg: true
  assets:
    outputs:
      class_name: Assets